# `U` is a predefined unit of measure that means 19.05mm, which is MX spacing
units:
  # Proxy Spacing Variables for easy changing to choc/mx
  kx: u
  ky: u
  # Padding Variables
  px: kx + 2
  py: ky + 2
  center_x: 112.65
  center_y: -127
points:
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor.shift: [100, -100]
      key:
        padding: 1ky
        spread: 1kx
      rotate: -15
      columns:
        pinky:
          rows.bottom:
            rotate: 90
          rows.home:
            rotate: -90
            shift: [1kx, -1kx]
        ring.key:
          stagger: 0.25kx
        middle.key.stagger: 0.25kx
        index.key.stagger: -0.25kx
        inner:
          key.stagger: -0.15kx
          rows.top.rotate: 90
      rows:
        bottom.padding: kx
        home.padding: kx
        top.padding: kx
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [0.6kx, -1.2kx]
        rotate: -10
      columns:
        tucky:
          key.name: thumb_tucky
        reachy:
          key.spread: kx
          key.splay: -14
          key.stagger: 3
          key.origin: [-0.5kx, -0.5kx]
          key.shift: [1, 0]
          key.rotate: 90
          key.width: 1.5kx
          key.name: thumb_reachy
    helper:
      key.skip: true
      anchor.shift: [100 - 1.25kx, -100 -3.25kx]
      columns:
        pinky:
        ring:
        middle:
        index:
        inner:
      rows:
        thumb:
        bottom:
          shift: [0, kx]
        home:
        top:
outlines:
  thumb:
    - what: rectangle
      where: thumb_reachy
      bound: true
      size: [1.5kx, ky]
  keys:
    - what: rectangle
      where: true
      size: [kx, kx]
  limits:
    - what: rectangle
      size: [100, 100]
      adjust.shift: [center_x, center_y]
  combo:
    - name: limits
    - operation: stack
      name: keys
    - operation: stack
      name: thumb
  pcb_outline:
    - what: polygon
      points:
        - shift: [center_x-50, center_y+50]
        - shift: [100, 0]
        - shift: [0, -100]
        - shift: [-40, 0]
        - shift: [-15, 15]
        - shift: [-45, 0]
      fillet: 2
  pcb_outline_combo:
    - name: pcb_outline
    - operation: stack
      name: keys
    - operation: stack
      name: limits
  case_outline:
    - what: polygon
      points:
        - shift: [center_x-57, center_y+56]
        - shift: [115, 0]
        - shift: [0, -115]
        - shift: [-40, 0]
        - shift: [-23.5, 23.5]
        - shift: [-51.5, 0]
      fillet: 2
  case_outline_combo:
    - name: case_outline
    - operation: stack
      name: pcb_outline
    - operation: stack
      name: keys
    - operation: stack
      name: thumb
pcbs:
  board:
    outlines.edge:
      outline: pcb_outline
      layer: Edge.Cuts
    footprints:
      keys:
        what: key-switches
        where: true
        params:
          from: "{{name}}"
          to: GND
          mx: true
          mx_hotswap: true
          mx_reverse: true
          mx_pth: true
          choc: true
          choc_hotswap: true
          choc_reverse: true
          choc_pth: true
          keycaps: true
      mcu:
        what: promicro-pretty
        where:
          - shift: [center_x - 34.8, center_y - 25]
        params:
          P7: matrix_pinky_top
          P18: matrix_ring_top
          P19: matrix_middle_top
          P20: matrix_index_top
          P21: matrix_inner_top
          P15: matrix_pinky_home
          P14: matrix_ring_home
          P16: matrix_middle_home
          P10: matrix_index_home
          P1: matrix_inner_home
          P2: matrix_pinky_bottom
          P3: matrix_ring_bottom
          P4: matrix_middle_bottom
          P5: matrix_index_bottom
          P6: matrix_inner_bottom
          P8: thumb_tucky
          P9: thumb_reachy
          P0: Switch18
          RAW: RAW
      trrs:
        what: trrs
        where:
          - shift: [center_x + 48, center_y + 51.7]
        params:
          reverse: true
          symmetric: true
          A: GND
          B: GND
          C: Switch18
          D: VCC
      reset:
        what: reset_button
        where:
          shift: [center_x - 4, center_y - 26]
          rotate: -90
        params:
          from: GND
          to: RST
      reset2:
        what: b3u1000p
        where:
          shift: [center_x - 4, center_y - 26]
          rotate: -90
        params:
          r1: GND
          r2: RST
      slider:
        what: slider_threeway
        where:
          shift: [center_x - 11, center_y - 33.5]
          rotate: 180
        params:
          from: Bplus
          left: RAW
          right: ''
          reversible: true
      jst:
        what: jstph_reversible
        where:
          shift: [center_x-11, center_y-17]
        params:
          pos: Bplus
          neg: GND
