name: 'Render pcb'
description: 'Get front and back images for pcb'
inputs:
  pcb_input_file:
    description: 'Kicad input file'
    required: true
  image_base:
    description: 'image output file base'
    required: true
  style:
    description: 'style json'
    default: style.json
runs:
  using: 'docker'
  image: 'docker://yaqwsx/kikit:v1.3.0-v7'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
     pcbdraw plot --style ${{ inputs.style }} $GITHUB_WORKSPACE/${{ inputs.pcb_input_file }} $GITHUB_WORKSPACE/${{ inputs.image_base }}-front.png;
     pcbdraw plot --style ${{ inputs.style }} --side back $GITHUB_WORKSPACE/${{ inputs.pcb_input_file }} $GITHUB_WORKSPACE/${{ inputs.image_base }}-back.png;
