on: 
  push:
    paths:
      - 'routed_pcb/board.kicad_pcb'
      - '.github/workflows/manual_route.yml'
  workflow_dispatch:

name: Generate From Manual Route
jobs:
  Image:
    uses: ./.github/workflows/image_gen.yml
    secrets:
      PAT: ${{ secrets.PAT }}
  Gerber:
    runs-on: ubuntu-latest
    name: Generate_gerbers
    container: docker://yaqwsx/kikit:v1.3.0-v7
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: generate gerbers
        run: kikit fab jlcpcb --no-drc routed_pcb/board.kicad_pcb output/
      - name: Persist output
        uses: actions/upload-artifact@v3
        with:
          name: gerbers
          path: output/gerber/*
